[package]
name = "riso8601"
version = "0.1.0"
authors = ["Suhail Patel <me@suhailpatel.com>"]
edition = "2018"

[lib]
name = "riso8601"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.11.0", features = ["extension-module"] }
